import type { Metadata } from "next";
import NavigationMenu from "./_components/navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "PCFC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavigationMenu>{children}</NavigationMenu>
      </body>
    </html>
  );
}
